name: fipe_agora
description: "Fipe Agora, um aplicativo que facilita a consulta de valores de veículos"
publish_to: 'none' 

version: 1.0.1+3

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  get_it: ^8.2.0
  go_router: ^16.2.1 
  equatable: ^2.0.7
  mockito: ^5.5.1
  dio: ^5.9.0
  skeletonizer: ^2.0.1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  share_plus: ^11.1.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  assets:
    - assets/images/
 
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400