// Mocks generated by Mockito 5.4.5 from annotations
// in fipe_agora/test/src/domain/usecase/get_yearmodel_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fipe_agora/src/domain/entities/brand_entity.dart' as _i6;
import 'package:fipe_agora/src/domain/entities/fipe_table_entity.dart' as _i2;
import 'package:fipe_agora/src/domain/entities/reference_table_entity.dart'
    as _i5;
import 'package:fipe_agora/src/domain/entities/vehicle_models_entity.dart'
    as _i7;
import 'package:fipe_agora/src/domain/entities/year_model_entity.dart' as _i8;
import 'package:fipe_agora/src/domain/repository/repository_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFipeTableEntity_0 extends _i1.SmartFake
    implements _i2.FipeTableEntity {
  _FakeFipeTableEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FipeRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockFipeRepositoryInterface extends _i1.Mock
    implements _i3.FipeRepositoryInterface {
  @override
  _i4.Future<List<_i5.ReferenceTableEntity>> getReferenceTable() =>
      (super.noSuchMethod(
            Invocation.method(#getReferenceTable, []),
            returnValue: _i4.Future<List<_i5.ReferenceTableEntity>>.value(
              <_i5.ReferenceTableEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.ReferenceTableEntity>>.value(
                  <_i5.ReferenceTableEntity>[],
                ),
          )
          as _i4.Future<List<_i5.ReferenceTableEntity>>);

  @override
  _i4.Future<List<_i6.BrandEntity>> getBrands({
    required String? tableCode,
    required String? vehicleCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
            }),
            returnValue: _i4.Future<List<_i6.BrandEntity>>.value(
              <_i6.BrandEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i6.BrandEntity>>.value(
              <_i6.BrandEntity>[],
            ),
          )
          as _i4.Future<List<_i6.BrandEntity>>);

  @override
  _i4.Future<List<_i7.VehicleModelsEntity>> getVehicleModels({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleModels, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
            }),
            returnValue: _i4.Future<List<_i7.VehicleModelsEntity>>.value(
              <_i7.VehicleModelsEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i7.VehicleModelsEntity>>.value(
                  <_i7.VehicleModelsEntity>[],
                ),
          )
          as _i4.Future<List<_i7.VehicleModelsEntity>>);

  @override
  _i4.Future<List<_i8.YearByModelEntity>> getYearByModel({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? modelCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getYearByModel, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #modelCode: modelCode,
            }),
            returnValue: _i4.Future<List<_i8.YearByModelEntity>>.value(
              <_i8.YearByModelEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i8.YearByModelEntity>>.value(
                  <_i8.YearByModelEntity>[],
                ),
          )
          as _i4.Future<List<_i8.YearByModelEntity>>);

  @override
  _i4.Future<_i2.FipeTableEntity> getFipeTable({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? yearId,
    required String? modelCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFipeTable, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #yearId: yearId,
              #modelCode: modelCode,
            }),
            returnValue: _i4.Future<_i2.FipeTableEntity>.value(
              _FakeFipeTableEntity_0(
                this,
                Invocation.method(#getFipeTable, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                  #yearId: yearId,
                  #modelCode: modelCode,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.FipeTableEntity>.value(
              _FakeFipeTableEntity_0(
                this,
                Invocation.method(#getFipeTable, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                  #yearId: yearId,
                  #modelCode: modelCode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.FipeTableEntity>);
}
