// Mocks generated by Mockito 5.4.4 from annotations
// in fipe_agora/test/src/domain/usecase/get_car_models_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fipe_agora/src/domain/entities/brand_entity.dart' as _i5;
import 'package:fipe_agora/src/domain/entities/car_models_entity.dart' as _i6;
import 'package:fipe_agora/src/domain/entities/reference_table_entity.dart'
    as _i4;
import 'package:fipe_agora/src/domain/repository/repository_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FipeRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockFipeRepositoryInterface extends _i1.Mock
    implements _i2.FipeRepositoryInterface {
  @override
  _i3.Future<List<_i4.ReferenceTableEntity>> getReferenceTable() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReferenceTable,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ReferenceTableEntity>>.value(
            <_i4.ReferenceTableEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ReferenceTableEntity>>.value(
                <_i4.ReferenceTableEntity>[]),
      ) as _i3.Future<List<_i4.ReferenceTableEntity>>);

  @override
  _i3.Future<List<_i5.BrandEntity>> getBrands({
    required String? tableCode,
    required String? vehicleCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrands,
          [],
          {
            #tableCode: tableCode,
            #vehicleCode: vehicleCode,
          },
        ),
        returnValue:
            _i3.Future<List<_i5.BrandEntity>>.value(<_i5.BrandEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.BrandEntity>>.value(<_i5.BrandEntity>[]),
      ) as _i3.Future<List<_i5.BrandEntity>>);

  @override
  _i3.Future<List<_i6.CarModelsEntity>> getCarModels({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? modelCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCarModels,
          [],
          {
            #tableCode: tableCode,
            #vehicleCode: vehicleCode,
            #brandCode: brandCode,
            #modelCode: modelCode,
          },
        ),
        returnValue: _i3.Future<List<_i6.CarModelsEntity>>.value(
            <_i6.CarModelsEntity>[]),
        returnValueForMissingStub: _i3.Future<List<_i6.CarModelsEntity>>.value(
            <_i6.CarModelsEntity>[]),
      ) as _i3.Future<List<_i6.CarModelsEntity>>);
}
