// Mocks generated by Mockito 5.4.5 from annotations
// in fipe_agora/test/src/data/repository/fipe_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fipe_agora/src/data/datasource/fipe_datasource_interface.dart'
    as _i3;
import 'package:fipe_agora/src/data/models/brands_model.dart' as _i6;
import 'package:fipe_agora/src/data/models/fipe_table_model.dart' as _i2;
import 'package:fipe_agora/src/data/models/reference_table_model.dart' as _i5;
import 'package:fipe_agora/src/data/models/vehicle_model.dart' as _i7;
import 'package:fipe_agora/src/data/models/year_model.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFipeTableModel_0 extends _i1.SmartFake
    implements _i2.FipeTableModel {
  _FakeFipeTableModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FipeDatasourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockFipeDatasourceInterface extends _i1.Mock
    implements _i3.FipeDatasourceInterface {
  @override
  _i4.Future<List<_i5.ReferenceTableModel>> getReferenceTable() =>
      (super.noSuchMethod(
            Invocation.method(#getReferenceTable, []),
            returnValue: _i4.Future<List<_i5.ReferenceTableModel>>.value(
              <_i5.ReferenceTableModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.ReferenceTableModel>>.value(
                  <_i5.ReferenceTableModel>[],
                ),
          )
          as _i4.Future<List<_i5.ReferenceTableModel>>);

  @override
  _i4.Future<List<_i6.BrandModel>> getBrands({
    required String? tableCode,
    required String? vehicleCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
            }),
            returnValue: _i4.Future<List<_i6.BrandModel>>.value(
              <_i6.BrandModel>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i6.BrandModel>>.value(
              <_i6.BrandModel>[],
            ),
          )
          as _i4.Future<List<_i6.BrandModel>>);

  @override
  _i4.Future<List<_i7.VehicleModels>> getVehicleModels({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleModels, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
            }),
            returnValue: _i4.Future<List<_i7.VehicleModels>>.value(
              <_i7.VehicleModels>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i7.VehicleModels>>.value(
                  <_i7.VehicleModels>[],
                ),
          )
          as _i4.Future<List<_i7.VehicleModels>>);

  @override
  _i4.Future<List<_i8.YearByModel>> getYearByModel({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? modelCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getYearByModel, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #modelCode: modelCode,
            }),
            returnValue: _i4.Future<List<_i8.YearByModel>>.value(
              <_i8.YearByModel>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.YearByModel>>.value(
              <_i8.YearByModel>[],
            ),
          )
          as _i4.Future<List<_i8.YearByModel>>);

  @override
  _i4.Future<_i2.FipeTableModel> getFipeTable({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? yearId,
    required String? modelCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFipeTable, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #yearId: yearId,
              #modelCode: modelCode,
            }),
            returnValue: _i4.Future<_i2.FipeTableModel>.value(
              _FakeFipeTableModel_0(
                this,
                Invocation.method(#getFipeTable, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                  #yearId: yearId,
                  #modelCode: modelCode,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.FipeTableModel>.value(
              _FakeFipeTableModel_0(
                this,
                Invocation.method(#getFipeTable, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                  #yearId: yearId,
                  #modelCode: modelCode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.FipeTableModel>);
}
