// Mocks generated by Mockito 5.4.5 from annotations
// in fipe_agora/test/src/data/repository/fipe_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fipe_agora/src/data/datasource/fipe_datasource_interface.dart'
    as _i4;
import 'package:fipe_agora/src/data/models/brands_model.dart' as _i7;
import 'package:fipe_agora/src/data/models/fipe_table_model.dart' as _i3;
import 'package:fipe_agora/src/data/models/model_by_year_model.dart' as _i9;
import 'package:fipe_agora/src/data/models/reference_table_model.dart' as _i6;
import 'package:fipe_agora/src/data/models/vehicle_model.dart' as _i2;
import 'package:fipe_agora/src/data/models/year_model.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVehicleModels_0 extends _i1.SmartFake implements _i2.VehicleModels {
  _FakeVehicleModels_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFipeTableModel_1 extends _i1.SmartFake
    implements _i3.FipeTableModel {
  _FakeFipeTableModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FipeDatasourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockFipeDatasourceInterface extends _i1.Mock
    implements _i4.FipeDatasourceInterface {
  @override
  _i5.Future<List<_i6.ReferenceTableModel>> getReferenceTable() =>
      (super.noSuchMethod(
            Invocation.method(#getReferenceTable, []),
            returnValue: _i5.Future<List<_i6.ReferenceTableModel>>.value(
              <_i6.ReferenceTableModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i6.ReferenceTableModel>>.value(
                  <_i6.ReferenceTableModel>[],
                ),
          )
          as _i5.Future<List<_i6.ReferenceTableModel>>);

  @override
  _i5.Future<List<_i7.BrandModel>> getBrands({
    required String? tableCode,
    required String? vehicleCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
            }),
            returnValue: _i5.Future<List<_i7.BrandModel>>.value(
              <_i7.BrandModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i7.BrandModel>>.value(
              <_i7.BrandModel>[],
            ),
          )
          as _i5.Future<List<_i7.BrandModel>>);

  @override
  _i5.Future<_i2.VehicleModels> getVehicleModels({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVehicleModels, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
            }),
            returnValue: _i5.Future<_i2.VehicleModels>.value(
              _FakeVehicleModels_0(
                this,
                Invocation.method(#getVehicleModels, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.VehicleModels>.value(
              _FakeVehicleModels_0(
                this,
                Invocation.method(#getVehicleModels, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.VehicleModels>);

  @override
  _i5.Future<List<_i8.YearModel>> getYearModel({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? modelCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getYearModel, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #modelCode: modelCode,
            }),
            returnValue: _i5.Future<List<_i8.YearModel>>.value(
              <_i8.YearModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i8.YearModel>>.value(
              <_i8.YearModel>[],
            ),
          )
          as _i5.Future<List<_i8.YearModel>>);

  @override
  _i5.Future<List<_i9.ModelByYearModel>> getModelByYear({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? year,
    required String? fuelCode,
    required String? yearModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getModelByYear, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #year: year,
              #fuelCode: fuelCode,
              #yearModel: yearModel,
            }),
            returnValue: _i5.Future<List<_i9.ModelByYearModel>>.value(
              <_i9.ModelByYearModel>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i9.ModelByYearModel>>.value(
                  <_i9.ModelByYearModel>[],
                ),
          )
          as _i5.Future<List<_i9.ModelByYearModel>>);

  @override
  _i5.Future<_i3.FipeTableModel> getFipeTable({
    required String? tableCode,
    required String? vehicleCode,
    required String? brandCode,
    required String? year,
    required String? fuelCode,
    required String? yearModel,
    required String? modelCode,
    required String? consultType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFipeTable, [], {
              #tableCode: tableCode,
              #vehicleCode: vehicleCode,
              #brandCode: brandCode,
              #year: year,
              #fuelCode: fuelCode,
              #yearModel: yearModel,
              #modelCode: modelCode,
              #consultType: consultType,
            }),
            returnValue: _i5.Future<_i3.FipeTableModel>.value(
              _FakeFipeTableModel_1(
                this,
                Invocation.method(#getFipeTable, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                  #year: year,
                  #fuelCode: fuelCode,
                  #yearModel: yearModel,
                  #modelCode: modelCode,
                  #consultType: consultType,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.FipeTableModel>.value(
              _FakeFipeTableModel_1(
                this,
                Invocation.method(#getFipeTable, [], {
                  #tableCode: tableCode,
                  #vehicleCode: vehicleCode,
                  #brandCode: brandCode,
                  #year: year,
                  #fuelCode: fuelCode,
                  #yearModel: yearModel,
                  #modelCode: modelCode,
                  #consultType: consultType,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.FipeTableModel>);
}
